
spring:
  main:
    web-application-type: servlet  # 是否以web形式启动 none:否  servlet:是
  profiles:
    active: dev   # 选择启动环境 : dev   test  prod
  application:
    name: SpringBootTemplate   # 项目名称

#  security:
#    user:
#      name: user
#      password: user
#      roles: admin,users
knife4j:
  production: false

logging:
  config: classpath:logback-${spring.profiles.active}-spring.xml   # 跟随启动环境选择日志





